### ISSUE TITLE
Add support for Backdrop

### ISSUE THREAD

**Issue by herbdool** [Skvare/com.skvare.cmsuser#3]
Thanks for the extension, it looks great!

Could you add support for Backdrop? It would be very similar to Drupal 7 function. I think you'd only need to change `drupal_` to `backdrop_`.

**Comment by sunilpawar** [comment]
@herbdool i have added support for backdrupa, check master branch.

**Comment by herbdool** [comment]
@sunilpawar thank you! I'll hopefully take a look soon.

**Comment by sunilpawar** [comment]
@herbdool closing ticket, re open if it is not working ...
